# Generated by Django 5.2.3 on 2025-06-15 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('identificador_unico', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DatoBiometrico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_biometrico', models.CharField(choices=[('rostro', 'Rostro'), ('huella', 'Huella Dactilar')], max_length=10)),
                ('ruta_simulada', models.ImageField(upload_to='biometric_data/')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos_biometricos', to='app.persona')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_hora_salida', models.DateTimeField(blank=True, null=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.persona')),
            ],
        ),
    ]
